project:
  type: website

website:
  title: "haileycsy"
  sidebar:
    font-size: small
    style: "docked"
    background: "#453a60"
    search: true
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/hailey-sy-cheong/
      - icon: diagram-3-fill
        href: https://public.tableau.com/app/profile/hailey.cheong
      - icon: github
        href: https://github.com/haileycsy
    contents:
      - section: "Home"
        contents:
          - index.qmd
          - about.qmd
      - section: "Hands-on Exercises"
        contents:
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
      - section: "In-class Exercises"
        contents:
          - text: "In-class Exercise 1"
            href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
      - section: "Take Home Exercises"
        contents:
          - text: "Take Home Exercise 1"
format:
  html:
    theme: flatly
    mainfont: Bahnschrift
    css: styles.css
    toc: true

editor: visual

