project:
  type: website

website:
  title: haileycsy
  favicon: "Images/apple-touch-icon.png"
  sidebar:
    logo: "Images/Name_Logo2.png"
    font-size: x-small
    style: "docked"
    background: "#3A3B60"
    alignment: center
    collapse-level: 1
    search: true
    color: "#F8F3E6"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/hailey-sy-cheong/
        aria-label: Linkedin
      - icon: diagram-3-fill
        href: https://public.tableau.com/app/profile/hailey.cheong
        aria-label: Tableau
      - icon: github
        href: https://github.com/haileycsy
        aria-label: Github
    contents:
      - section: "Home"
        contents:
          - index.qmd
          - text: "Hello World"
            href: about.html
      - section: "Hands-on Exercises"
        contents:
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
      - section: "In-class Exercises"
        contents:
          - text: "In-class Exercise 1"
            href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
      - section: "Take Home Exercises"
        contents:
          - text: "Take Home Exercise 1"
format:
  html:
    theme: flatly
    backgroundcolor: "#F8F3E6"
    mainfont: Consolas
    css: styles.css
    toc: true

editor: visual


