project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise 1"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands_on_Ex01/Hands-on_Ex01.html"
            
    right:
        - href: index.qmd
          text: Home
        - about.qmd

format:
  html:
    theme: minty
    mainfont: Bahnschrift
    css: styles.css
    toc: true

editor: visual

