project:
  type: website

website:
  title: "haileycsy"
  image: "Images/Name_LogoL.png"
  favicon: "Images/apple-touch-icon.png"
  page-navigation: true
  navbar:
    logo: "Images/Name_Logo2.png"
    title: false
    collapse-below: lg
    search: true
    left:
      - text: "{{< fa house-chimney-window >}} Home"
        menu: 
          - text: "{{< fa house-chimney-window >}} Home"
            href: index.qmd
          - text: "{{< fa robot >}} Hello World"
            href: about.html
      - text: "{{< fa hand-sparkles >}} Hands-on Ex"
        menu:
          - text: "Hands-on Ex 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
          - text: "Hands-on Ex 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
          - text: "Hands-on Ex 3"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html
      - text: "{{< fa pen-to-square >}} In-class Ex"
        menu:
          - text: "In-class Ex"
      - text: "{{< fa magnifying-glass-chart >}} Take-home Ex"
        menu:
          - text: "Take-home Ex 1"
      - text: "{{< fa laptop-code >}} Projects"
        menu:
          - text: "Shiny"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/hailey-sy-cheong/
        aria-label: Linkedin
      - icon: diagram-3-fill
        href: https://public.tableau.com/app/profile/hailey.cheong
        aria-label: Tableau
      - icon: github
        href: https://github.com/haileycsy
        aria-label: Github
  page-footer:
    right: |
      Copyright 2023![](Images/Name_Logo3.png){fig-alt="Name_logo" width=100px}
format:
  html:
    toc: true
    theme: 
      - cosmo
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap
    css: styles.css
    

editor: visual


