---
title: "Hands on Exercise 2"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
---

# Load and Install R Packages

```{r}
pacman::p_load(ggrepel, patchwork, 
               ggthemes, hrbrthemes, InraeThemes,
               tidyverse) 
```

# Importing the data
```{r, message=FALSE}
exam_data <- read_csv("data/Exam_data.csv")
```

# Overview of the data
```{r}
summary(exam_data)
```

# Plotting Practice
## Annotations with ggrepel
A comparison between annotations using geom_label(), geom_text() and package ggrepel

::: panel-tabset

### with ggrepel

```{r, warning=FALSE}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              linewidth=0.5,
              formula = y~x) +  
  geom_label_repel(aes(label = ID), 
                   fontface="bold") +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  labs(x="Math",
       y="English",
       title="Correlation between English and Maths scores for Primary 3",
       subtitle="There is a positive correlation between English and Math Scores") +
  theme(text=element_text(family="mono"),
        plot.background=element_rect(fill="#F8F3E6",colour="#F8F3E6"))
```

### without

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              linewidth=0.5,
              formula = y~x) +  
  geom_label(aes(label = ID), 
             hjust = .5, 
             vjust = -.5) +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  labs(x="Math",
       y="English",
       title="Correlation between English and Maths scores for Primary 3",
       subtitle="There are too many annotations to see the points clearly") +
  theme(plot.background=element_rect(fill="#F8F3E6",colour="#F8F3E6"))
```

:::