---
title: "Take-home Exercise 3"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    code-fold: true
    code-summary: "code block"
---

```{r intstall-packages}
#| code-fold: false
pacman::p_load(jsonlite, tidyverse, DT, lubridate, Hmisc, 
               urbnthemes,visNetwork, tidygraph, ggraph, 
               ggiraph, igraph, scales, ggplot2, 
               gganimate, ggstatsplot, ggrain, ggridges, 
               graphlayouts, plotly, patchwork, kableExtra, 
               ggpubr, ggrepel)
```

## Loading the json Data

Use `jsonlite` package to read .json files

```{r load-mc2}
#| code-fold: false
mc3 <- jsonlite::fromJSON("data/MC3.json")
```

```{r}
mc3_links <- as_tibble(mc3$links)

mc3_nodes <- as_tibble(mc3$nodes) %>%
  select(id, type, country, revenue_omu, product_services)
```

## Data Health

::: {.panel-tabset}

## **Nodes**

**I. Checking for Missing Values:**

```{r}
# Check for columns with missing values
colSums(is.na(mc3_nodes))
```

**II. Splitting product_services column by delimiter:**

`separate_longer_delim` is used to split the **product_services** column due to the varying number of components:

```{r}
#| warning: false
mc3_nodes_unnest <- mc3_nodes %>%
  unnest(id) %>%
  unnest(type) %>%
  unnest(country)

```

```{r}

```

## **Links**

**I. Checking for Missing Values:**

```{r}
# Check for columns with missing values
colSums(is.na(mc3_links))
```

**II. Checking for Duplicates:**

```{r}
mc3_links[duplicated(mc3_links),]
```
